# Generated by Django 4.1 on 2023-10-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="id",
        ),
        migrations.AlterField(
            model_name="students",
            name="name",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.IntegerField(max_length=4)),
                ("math", models.IntegerField(max_length=4)),
                ("science", models.IntegerField(max_length=4)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study.students"
                    ),
                ),
            ],
        ),
    ]
