# Generated by Django 4.1 on 2023-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_remove_students_id_alter_students_name_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="english",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="score",
            name="math",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="score",
            name="science",
            field=models.IntegerField(),
        ),
    ]
