# Generated by Django 4.1 on 2023-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0003_alter_score_english_alter_score_math_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
